---
- hosts: all
  connection: local

  vars_files:
    - configuration/default.config.yml
    - configuration/dotfiles.yml
    - configuration/homebrew.yml
    - configuration/mas.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: install_mas
      tags: ['mas']
    - role: gantsign.oh-my-zsh
      when: install_ohmyzsh
      tags: ['ohmyzsh']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/macos.yml
      tags: ['macos']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
