---
downloads: ~/.ansible-downloads/

#####################
## Feature Toggles ##
#####################

# Checkout Dotfile-Repository and Symlink them
configure_dotfiles: no

# Set macOS defaults (Requires configure_dotfiles)
configure_macos: yes
configure_macos_dock: yes

# Install oh-my-zsh
install_ohmyzsh: yes

# Install Mac App Store Apps
install_mas: yes

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
